import type { ReportData, AnalyzerOutput, TodoItem, SkillFile } from './types.js';

export function analyze(data: ReportData): AnalyzerOutput {
  const todos = buildTodos(data);
  const claudeMdAdditions = buildClaudeMdAdditions(data);
  const settingsJson = buildSettings(data);
  const skills = buildSkills(data);
  const readmeContent = buildReadme();
  return { todos, claudeMdAdditions, settingsJson, skills, readmeContent };
}

function buildTodos(data: ReportData): TodoItem[] {
  const todos: TodoItem[] = [];

  // Friction-derived tasks (High priority)
  for (const friction of data.frictions) {
    const title = friction.title.toLowerCase();
    if (title.includes('premature') || title.includes('verification')) {
      todos.push({
        task: 'Add verify-first rule to CLAUDE.md + create insights-review skill',
        steps: '1. Copy verify-first rule from CLAUDE.md-additions.md to your CLAUDE.md\n2. Copy insights-review.SKILL.md to .claude/skills/\n3. Test: run /insights-review on your next task',
        priority: 'High',
        estTime: '5 min',
        expectedWin: '~30% fewer wrong approaches (currently 46 incidents)',
        source: 'friction',
      });
    } else if (title.includes('css') || title.includes('styling')) {
      todos.push({
        task: 'Create CSS guardrails skill + add Shadow DOM rules to CLAUDE.md',
        steps: '1. Copy CSS & Styling rules from CLAUDE.md-additions.md\n2. Copy fix-css.SKILL.md to .claude/skills/\n3. Test: run /fix-css on your next CSS task',
        priority: 'High',
        estTime: '5 min',
        expectedWin: '~50% fewer CSS iterations (currently 11+ sessions affected)',
        source: 'friction',
      });
    } else if (title.includes('debug') || title.includes('root cause') || title.includes('wrong')) {
      todos.push({
        task: 'Create structured debugging skill + add debugging rules to CLAUDE.md',
        steps: '1. Copy Debugging rules from CLAUDE.md-additions.md\n2. Copy debug-structured.SKILL.md to .claude/skills/\n3. Test: run /debug-structured on your next bug',
        priority: 'High',
        estTime: '5 min',
        expectedWin: '~40% fewer wrong root cause investigations',
        source: 'friction',
      });
    }
  }

  // CLAUDE.md item tasks (High priority)
  for (const item of data.claudeMdItems) {
    const shortCode = item.code.length > 80 ? item.code.slice(0, 80) + '...' : item.code;
    todos.push({
      task: `Add CLAUDE.md rule: "${shortCode}"`,
      steps: '1. Open your project CLAUDE.md\n2. Paste the rule under the appropriate section\n3. Save',
      priority: 'High',
      estTime: '2 min',
      expectedWin: 'Prevents repeated friction pattern',
      source: 'claude-md',
    });
  }

  // Feature tasks (Medium priority)
  for (const feature of data.features) {
    todos.push({
      task: `Set up ${feature.title}`,
      steps: feature.examples.length > 0
        ? `1. Review the example in the generated files\n2. Copy configuration to your project\n3. Test it works`
        : `1. Read the feature description\n2. Configure in your project\n3. Test`,
      priority: 'Medium',
      estTime: '10 min',
      expectedWin: feature.oneliner,
      source: 'feature',
    });
  }

  // Pattern tasks (Medium/Low priority)
  for (const pattern of data.patterns) {
    todos.push({
      task: `Try workflow: ${pattern.title}`,
      steps: '1. Copy the suggested prompt from insights-README.md\n2. Paste it at the start of your next relevant session\n3. Evaluate if it reduces friction',
      priority: 'Medium',
      estTime: '5 min',
      expectedWin: pattern.summary,
      source: 'pattern',
    });
  }

  return todos;
}

function buildClaudeMdAdditions(data: ReportData): string {
  // Categorize CLAUDE.md items by detecting keywords in their code
  const sections: Record<string, { code: string; why: string }[]> = {
    'General Rules': [],
    'CSS & Styling': [],
    'Testing': [],
    'Debugging': [],
  };

  for (const item of data.claudeMdItems) {
    const lower = item.code.toLowerCase();
    if (lower.includes('css') || lower.includes('shadow dom') || lower.includes('styling') || lower.includes('scoped')) {
      sections['CSS & Styling'].push(item);
    } else if (lower.includes('test') || lower.includes('playwright') || lower.includes('vitest') || lower.includes('mock')) {
      sections['Testing'].push(item);
    } else if (lower.includes('debug') || lower.includes('root cause') || lower.includes('reproduce') || lower.includes('diagnostic')) {
      sections['Debugging'].push(item);
    } else {
      sections['General Rules'].push(item);
    }
  }

  let md = '# CLAUDE.md Additions\n\n';
  md += '> Generated by claude-insights. Copy the relevant sections into your project\'s CLAUDE.md.\n\n';

  for (const [section, items] of Object.entries(sections)) {
    if (items.length === 0) continue;
    md += `## ${section}\n\n`;
    for (const item of items) {
      md += `${item.code}\n\n`;
      if (item.why) {
        md += `> _Why: ${item.why}_\n\n`;
      }
    }
  }

  return md;
}

function buildSettings(data: ReportData): object {
  // Extract hook configurations from feature examples
  const hooksFeature = data.features.find(f => f.title.toLowerCase().includes('hook'));

  if (hooksFeature && hooksFeature.examples.length > 0) {
    // Try to extract JSON from the example code
    const example = hooksFeature.examples[0];
    const jsonMatch = example.match(/\{[\s\S]*"hooks"[\s\S]*\}/);
    if (jsonMatch) {
      try {
        // Clean up the example — remove JS comments
        const cleaned = jsonMatch[0].replace(/\/\/.*$/gm, '').trim();
        return JSON.parse(cleaned);
      } catch {
        // Fallback to a sensible default based on the report content
      }
    }
  }

  // Default hooks based on report analysis (Vue/TS project)
  return {
    hooks: {
      postEdit: {
        command: 'npx vue-tsc --noEmit --pretty 2>&1 | head -20',
        description: 'Type-check after edits to catch issues early',
      },
    },
  };
}

function buildSkills(data: ReportData): SkillFile[] {
  const skills: SkillFile[] = [];

  // 1. insights-review skill — verify-first workflow
  const verifyPattern = data.patterns.find(p =>
    p.title.toLowerCase().includes('premature') || p.title.toLowerCase().includes('friction')
  );
  const verifyFriction = data.frictions.find(f =>
    f.title.toLowerCase().includes('premature') || f.title.toLowerCase().includes('verification')
  );

  skills.push({
    filename: 'insights-review.SKILL.md',
    content: `---
name: insights-review
description: Verify assumptions against codebase before proposing changes
---

## Instructions

${verifyPattern?.prompt || 'Before making any changes, first: 1) Find 2-3 similar implementations in this codebase and show me the patterns they use, 2) Identify any constraints (Shadow DOM, scoped styles, existing test patterns), 3) Propose your approach referencing those patterns. Only after I approve, start implementing.'}

## Why This Exists

${verifyFriction?.description || 'Claude frequently proposes fixes before verifying them against the codebase, leading to wrong approaches.'}

## Examples of What Goes Wrong

${verifyFriction?.examples.map(e => `- ${e}`).join('\n') || '- Proposing solutions without checking existing patterns'}
`,
  });

  // 2. fix-css skill — CSS guardrails
  const cssFriction = data.frictions.find(f =>
    f.title.toLowerCase().includes('css') || f.title.toLowerCase().includes('styling')
  );
  const cssPattern = data.patterns.find(p =>
    p.title.toLowerCase().includes('css') || p.title.toLowerCase().includes('scope')
  );
  const cssCmdItem = data.claudeMdItems.find(item =>
    item.code.toLowerCase().includes('css') || item.code.toLowerCase().includes('shadow dom')
  );

  skills.push({
    filename: 'fix-css.SKILL.md',
    content: `---
name: fix-css
description: CSS fixes with Shadow DOM awareness and scoping guardrails
---

## Instructions

${cssPattern?.prompt || 'Fix the CSS issue with these constraints: 1) Do NOT modify any global/shared styles, 2) Verify your fix doesn\'t affect other components by checking their CSS inheritance, 3) Use the most narrowly-scoped selector possible, 4) Show me which other components could be affected before applying.'}

## Rules

${cssCmdItem?.code || 'When working with CSS in Vue components (especially Shadow DOM, flyouts, and scoped styles): 1) CSS custom properties don\'t cross Shadow DOM boundaries, 2) Always scope CSS fixes narrowly to avoid breaking other components, 3) Test that changes don\'t regress other flyout tabs or views.'}

## Why This Exists

${cssFriction?.description || 'CSS and visual styling tasks are especially painful, with Claude cycling through broken approaches around Shadow DOM boundaries, scoped selectors, and icon sizing.'}

## Examples of What Goes Wrong

${cssFriction?.examples.map(e => `- ${e}`).join('\n') || '- Broad CSS fixes breaking other components'}
`,
  });

  // 3. debug-structured skill — structured debugging
  const debugFriction = data.frictions.find(f =>
    f.title.toLowerCase().includes('debug') || f.title.toLowerCase().includes('root cause')
  );
  const debugPattern = data.patterns.find(p =>
    p.title.toLowerCase().includes('debug') || p.title.toLowerCase().includes('reproduction')
  );
  const debugCmdItem = data.claudeMdItems.find(item =>
    item.code.toLowerCase().includes('debug') || item.code.toLowerCase().includes('root cause')
  );

  skills.push({
    filename: 'debug-structured.SKILL.md',
    content: `---
name: debug-structured
description: Structured debugging protocol - reproduce first, verify before fixing
---

## Instructions

${debugPattern?.prompt || 'Debug this issue using a structured approach: 1) First, can we reproduce it locally? Try to reproduce before theorizing. 2) If not reproducible, what exact conditions trigger it? 3) Add diagnostic logging to ONLY the specific code path involved. 4) Do NOT propose a fix until we have confirmed evidence of the root cause.'}

## Rules

${debugCmdItem?.code || 'When debugging production or intermittent issues, do NOT jump to conclusions about root cause. First: reproduce locally. Second: add targeted diagnostic logging. Third: only propose a fix when the root cause is confirmed with evidence.'}

## Why This Exists

${debugFriction?.description || 'Claude often locks onto an incorrect hypothesis early and spends significant effort debugging the wrong thing.'}

## Examples of What Goes Wrong

${debugFriction?.examples.map(e => `- ${e}`).join('\n') || '- Jumping to wrong root cause hypotheses'}
`,
  });

  return skills;
}

function buildReadme(): string {
  return `# Insights Output — Placement Guide

## Generated Files

| File | What It Is | Where To Put It |
|------|-----------|-----------------|
| \`CLAUDE.md-additions.md\` | Rules for Claude based on your friction patterns | Copy contents into your project's root \`CLAUDE.md\` |
| \`insights-todo.md\` | Prioritized task list with steps | Keep as reference, work through tasks |
| \`.claude/settings-insights.json\` | Hook configurations | Merge into your \`.claude/settings.json\` |
| \`.claude/skills/insights-review.SKILL.md\` | Verify-first workflow skill | Copy to your project's \`.claude/skills/\` |
| \`.claude/skills/fix-css.SKILL.md\` | CSS guardrails skill | Copy to your project's \`.claude/skills/\` |
| \`.claude/skills/debug-structured.SKILL.md\` | Structured debugging skill | Copy to your project's \`.claude/skills/\` |

## Quick Start

1. **CLAUDE.md**: Open \`CLAUDE.md-additions.md\`, copy the rules you want into your project's \`CLAUDE.md\`
2. **Settings**: Open \`.claude/settings-insights.json\`, merge the hooks config into your existing \`.claude/settings.json\`
3. **Skills**: Copy the \`.claude/skills/*.SKILL.md\` files into your project's \`.claude/skills/\` directory
4. **Test**: Start a new Claude Code session and try \`/insights-review\` on your next task

## Testing Skills

- \`/insights-review\` — Forces Claude to verify assumptions before proposing changes
- \`/fix-css\` — Applies CSS guardrails (Shadow DOM awareness, narrow scoping)
- \`/debug-structured\` — Enforces structured debugging (reproduce first, evidence-based fixes)
`;
}
